# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: pwsh 
      run: |
        # Install-PackageProvider -Name PowerShellGet -Force | Out-Null
        Install-Module -Name Pester -Force
        Install-Module -Name posh-git -Force
        Install-Module -Name platyPS -Force

    - name: Install dependencies
      shell: pwsh 
      run: |
        $Timestamp = Get-date -uformat "%Y%m%d-%H%M%S"
        $PSVersion = $PSVersionTable.PSVersion.Major
        $TestFile = "TestResults_PS$PSVersion`_$TimeStamp.xml"
        $Verbose = @{}
        
        #if($env:APPVEYOR_REPO_BRANCH -and $env:APPVEYOR_REPO_BRANCH -notlike "master")
        #{
        #    $Verbose.add("Verbose",$True)
        #}              
        
        Import-Module Pester -force
        Invoke-Pester @Verbose -Path ".\Tests" -OutputFormat NUnitXml -OutputFile ".\$TestFile" -PassThru |
            Export-Clixml -Path ".\PesterResults_PS$PSVersion`_$Timestamp.xml"
        
    - name: NUnit Reporter
      uses: MirrorNG/nunit-reporter@v1.0.5
      with:
        # github token
        access-token: ${{ secrets.GITHUB_TOKEN }}
        # glob to junit xml files
        path: PesterResults*.xml
        # max number of failed tests to include
        numFailures: 30
#  - ps: . .\build.ps1
